#!/usr/bin/env bash
# load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen 13402-lb-01\n\tbind :80\n\tbalance roundrobin\n\tserver 13402-web-01 34.204.185.3 check\n\tserver 13402-web-02 3.237.0.50 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start
